spring:
  application:
    name: employee-Info

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: c##micro
    password: micro
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: chaudharymoin21@gmail.com
    password: uflb fppg hhit mena
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    
server:
     port: 8089